# Generated by Django 5.1.1 on 2024-11-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IFC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('council_name', models.CharField(max_length=255)),
                ('position_name', models.CharField(max_length=255)),
                ('position_holder_name', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('chapter_affiliation', models.CharField(max_length=255)),
                ('position_holder_image', models.ImageField(default='councils/default.jpg', upload_to='councils/')),
            ],
        ),
        migrations.AlterField(
            model_name='fscuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
