# Generated by Django 5.1.1 on 2024-11-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FSC", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="council",
            field=models.CharField(default="none", max_length=100),
        ),
        migrations.AlterField(
            model_name="fscuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
