name: python lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  flake8-lint:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    name: Python Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.12.0
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "F401,E226,W504,E126"
          max-line-length: "125"
